messages:
  welcome: |
    Привет! Я — *PostFinder*, инструмент, который изменит твое взаимодействие с социальными сетями.

    Если вы постоянно теряетесь в ТОННЕ КОНТЕНТА,
    приходиться листать БЕСКОНЕЧНОЕ количество постов и никак не можете найти ТОТ САМЫЙ пост? То вы пришли в нужное место!

    *Команды:*
    - /help - показывает эту справку
    - /start - начало диалога
    - /find `<@channel> <Запрос>` - ищет ответ на Ваш вопрос в указанном канале

    _Например: /find @postfinder Как найти нужный пост в группе?_ 
    |
  paper_assist: |
    Привет! Пришли пожалуйста ссылку на статью или публикацию в формате PDF.